server:
  port: 8080
spring:
  application:
    name: rest-emulator
  profiles:
    active: DEV
  kafka:
    bootstrap-servers: localhost:9092
    topic: "messages"
    consumer-group: "messages-group"
logging:
  level:
    .: INFO